module.exports = {
  IventoryProducts: [
    {
      _id: '00001',
      price: '23500',
      discount: '22500',
      name: 'Karastan Soft Carpet Upright Vacuum',
      model: '(Model: KSC-7500)',
      image: 'https://dealers.sonicleanusa.com/img/KSC-7500.jpg',
    },
    {
      _id: '00002',
      price: '22500',
      discount: '21500',
      unit: 'unit',
      tooltip: 'Soft Carpet Upright Vacuum',
      name: 'Soft Carpet Upright Vacuum',
      description: '(Model: SFC-7000)',
      image: SFC_7000,
      multiples: 2,
    },
    {
      _id: '00003',
      price: '8000',
      discount: '7500',
      unit: 'unit',
      tooltip: 'Soniclean Handheld Vacuum',
      name: 'Soniclean Handheld Vacuum',
      description: '(Model: HH-0800)',
      image: HH_0800,
      multiples: 2,
    },
    {
      _id: '00004',
      price: '2000',
      discount: '2000',
      unit: 'package',
      tooltip: 'Soniclean Upright HEPA Filter Bags',
      name: 'Soniclean Upright HEPA Filter Bags',
      description: '(Model: SUF-0520)',
      image: SUF_0520,
      multiples: 4,
    },
    {
      _id: '00005',
      price: '1500',
      discount: '1500',
      unit: 'package',
      tooltip: 'Sonicfresh Fragrance Pods',
      name: 'Sonicfresh Fragrance Pods',
      description: '(Model: SFP-0100)',
      image: SFP_0100,
      multiples: 4,
    },
    {
      _id: '00006',
      price: '1500',
      discount: '1500',
      unit: 'package',
      tooltip: 'Soniclean Handheld HEPA Filter Bags',
      name: 'Soniclean Handheld HEPA Filter Bags',
      description: '(Model: SHF-0800)',
      image: SHF_0800,
      multiples: 4,
    },
  ],
};
